#Uncomment the next line to define a global platform for your project

target 'Monopoly Money Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Google-Mobile-Ads-SDK'

end
