#Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'Monopoly Money Counter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'

  # Pods for Monopoly Money Counter

  target 'Monopoly Money CounterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Monopoly Money CounterUITests' do
    # Pods for testing
  end

end
