# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Google_Ads_Test_App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google_Ads_Test_App

  pod 'Google-Mobile-Ads-SDK'

end
