# Uncomment the next line to define a global platform for your project

target 'MMCv2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MMCv2

  pod 'Google-Mobile-Ads-SDK'

end
